apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deployment
  namespace: winterschool
  labels:
    app: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-test
        image: nginx:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"      
        ports:
        - containerPort: 80
